# Makefile generated by http://MakeMyMakefile.com
#
# CC0 Public Domain
#
# To the extent possible under law, the author(s) have dedicated all
# copyright and related and neighboring rights to this software to the
# public domain worldwide. This software is distributed without any warranty.
#
# See http://creativecommons.org/publicdomain/zero/1.0/

# Output binary
BIN = roll

# Put all auto generated stuff to this build dir.
BUILD_DIR = ./build

SOURCE_DIR = .

# List of all the source files.
SOURCE = \
	main.c \

INCLUDES = \
	src \

CC = gcc

CC_FLAGS = -Wall -Wextra -Wfloat-equal -Wswitch-default -Wswitch-enum -Wno-unused-parameter -Wno-implicit-fallthrough -g -O2
LNK_FLAGS = 

# All .o files go to build dir.
C_OBJ = $(SOURCE:%.c=$(BUILD_DIR)/%.o)
OBJ = $(C_OBJ)


# Gcc/Clang will create these .d files containing dependencies.
DEP = $(OBJ:%.o=%.d)
# Include paths with a -I in front of them
INCLUDEPATHS = $(INCLUDES:%= -I %)

# Actual target of the binary - depends on all .o files.
$(BIN) : PreBuild $(OBJ)
	echo Linking...
	# Create build directories - same structure as sources.
	-mkdir -p $(@D) 2>/dev/null
	# Just link all the object files.
	$(CC) $(OBJ) $(LNK_FLAGS) -o $(BIN)

# Include all .d files
-include $(DEP)

# Build target for every single object file.
# The potential dependency on header files is covered
# by calling `-include $(DEP)`.

$(BUILD_DIR)/%.o : $(SOURCE_DIR)/%.c
	echo Compiling $(notdir $<)
	-mkdir -p $(@D) 2>/dev/null
	# The -MMD flags additionaly creates a .d file with
	# the same name as the .o file.
	$(CC) $(CC_FLAGS) $(INCLUDEPATHS) -MMD -c $< -o $@

# Install target: copies the binary to /usr/local/bin
install: $(BIN)
	install -m 755 $(BIN) /usr/local/bin/

# Uninstall target: removes the binary from /usr/local/bin
uninstall:
	rm -f /usr/local/bin/$(BIN)

.PHONY : clean
clean:
	# This should remove all generated files.
	-rm -r $(BUILD_DIR)
	-rm $(BIN)

.PHONY: PreBuild
PreBuild:
	# This is run at the start of the build

